services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1887:1883" # TCP MQTT
      - "9006:9001" # WebSocket MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config # бүх config dir-ийг өгнө
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
